modLoader="javafml"
loaderVersion="[37,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Death-Counter/issues"

[[mods]]
    modId="deathcounter"
    version="${file.jarVersion}" #mandatory
    displayName="Death Counter"
    displayURL="https://ichun.me/mods/death-counter/"
    authors="iChun"
    description='''
    Simple death counter for servers.
    '''

[[dependencies.deathcounter]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.deathcounter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"
